;=========================
InitiateSockets:
  push ebp
  mov ebp, esp
  
  ;WSAStartup
  push dword wsaData
  push dword 0x101
  call [WSAStartup]
  cmp eax, 0x0
  jne near .Error  ;error if not 0
  
  ;socket 
  push dword IPPROTO_TCP
  push dword SOCK_STREAM
  push dword AF_INET
  call [socket]
  cmp eax, INVALID_SOCKET
  je near .Error  ;error if INVALID_SOCKET
  mov dword [sockfd], eax
  
  ;setsockopt
  push dword 0x4
  push dword yes
  push dword SO_REUSEADDR
  push dword SOL_SOCKET
  push dword [sockfd]
  call [setsockopt]
  cmp eax, 0x0
  jne .Error  ;error if not 0
  
  ;set port
  push dword [port] ;it says htons takes a 16bit argument.. but if crashes if i do
  call [htons]
  mov [server+sockaddr_in.sin_port], ax  
  
  ;bind
  push dword sockaddr_in_size ;generated by iend
  push dword server
  push dword [sockfd]
  call [bind]
  cmp eax, 0x0
  jne .Error  ;error if not 0  
  jmp .Success
  
  .Error:
%if DEBUG == 1
    push dword MB_OK
    push dword title
    push dword sockError
    push byte 0x0
    call [MessageBoxA]
%endif
    mov eax, 0x0
    jmp .End
  
  .Success:
    mov eax, 0x1
    jmp .End
    
  .End:
    pop ebp
    ret
 
;=========================   
ConnectionHandler:
  push ebp
  mov ebp, esp
  sub esp, 0x4
  
  push dword 0x4
  push dword [sockfd]
  call [listen]
  .Loop    
    mov dword [ebx], sockaddr_in_size
    push dword ebx
    push dword client
    push dword [sockfd]
    call [accept]
    mov [ebp-4], eax

    ;login message
    push dword 0x0
    push dword loginMsgSize
    push dword loginMsg
    push dword [ebp-4]
    call [send] 
        
    ;handle commands
    push dword [ebp-4]
    call CommandHandler
    
    push dword [ebp-4]
    call [closesocket]
        
    jmp .Loop
  
  .End
    add esp, 0x4
    pop ebp
    ret
    
;=========================
Cleanup:
  push dword [sockfd]
  call [closesocket]

  call [WSACleanup]

  ret
